linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - unused
  disable:
    - errcheck  # Too strict for current codebase, enable in future

linters-settings:
  govet:
    check-shadowing: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata

output:
  format: colored-line-number
